
[[constraint]]
  name = "github.com/Clever/unicreds"
  branch = "master"

[[constraint]]
  name = "github.com/alecthomas/kingpin"

[[constraint]]
  name = "github.com/apex/log"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.0"

[[constraint]]
  name = "github.com/stretchr/testify"
